name: fenics-fk-env
channels:
  - conda-forge
dependencies:
  - python=3.8
  - fenics
  - mshr
  - gmsh
  - python-gmsh
  - h5py
  - matplotlib
  - scipy
  - trimesh
  - pytest
  - pip
  - pip:
    - meshio
    - fisher-kolmogorov