[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "fisher-kolmogorov"
version = "0.1.0"

[project.scripts]
fk-convergence = "fisher_kolmogorov.cli.fk_convergence:main"
fk-brain       = "fisher_kolmogorov.cli.fk_brain:main"
fk-run         = "fisher_kolmogorov.cli.fk_run:main"
fk-genmesh     = "fisher_kolmogorov.cli.fk_genmesh:main"
fk-convert     = "fisher_kolmogorov.cli.fk_convert:main"
fk-plot        = "fisher_kolmogorov.cli.fk_plot:main"